### PR TITLE
Bugfix default install

### LINKED ISSUE #17: Installation on RHEL doesn't work
- The packages built for Fedora are used, despite packages from Red Hat being available in the package repository. Might have to split up into several repositories, one for each platform.
- The packages depend on other packages from EPEL, which might not be available on the machine. Either remove dependencies on EPEL or explicitly state that EPEL is required in the documentation.

### LINKED ISSUE #19: Signing certificates doesn't work
`Signing failed: 256 at /var/www/cgi-bin/reqcert line 145.`

Tested on Fedora 27

### PR DESCRIPTION
**Pull request by oyvindhagberg**
This contains various bugfixes to make the default installation pass all tests on the target platforms (Fedora 27 and CentOS 7 at the moment).

This closes #17, and closes #19.

### CODE REVIEW

File: rpm/run_tests_on_vms.sh [hunk 1]
```diff
@@ -52,11 +60,15 @@ for IMAGE in "${IMAGES[@]}"; do
 	echo "Creating a VM with \"$IMAGE\""
 	NAME="voyager"
 	openstack server delete --wait $NAME 2>/dev/null # just to be sure
-	openstack server create --image "$IMAGE" --flavor m1.small \
-		--key-name jenkins_key --nic net-id=dualStack --wait $NAME \
-		> /dev/null
-	IP=$(openstack server list | grep $NAME | \
-		grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
+	IP=""
+	until [[ $IP != "" ]]; do
```
Comment (oyvindhagberg) [inline rpm/run_tests_on_vms.sh]: UH-IaaS has fixed the network problem, perhaps the loop should be removed now.
https://github.com/norcams/himlar/commit/7f21da53979ef458c2f23343faf0fcf3f0a401bc
